[package]
name = "astral"
version = "0.0.0"
edition = "2018"
authors = [ "Tim Diekmann <tim.diekmann@3dvision.de>" ]
repository = "https://github.com/astral-engine/astral"
documentation = "https://astral-engine.github.io/docs"
readme = "README.md"

[workspace]
members = [
    "src/libcore",
    "src/libresource",
    "src/libvideo",
]

[dependencies]
astral-core = { path = "src/libcore", version = "0.0.0", default-features = false }
astral-resource = { path = "src/libresource", version = "0.0.0", default-features = false }
astral-video = { path = "src/libvideo", version = "0.0.0", default-features = false }

[dev-dependencies]
rustc_version = "0.2"

[features]
max_level_off = ["astral-core/max_level_off"]
max_level_error = ["astral-core/max_level_error"]
max_level_warn = ["astral-core/max_level_warn"]
max_level_info = ["astral-core/max_level_info"]
max_level_debug = ["astral-core/max_level_debug"]
max_level_trace = ["astral-core/max_level_trace"]
release_max_level_off = ["astral-core/release_max_level_off"]
release_max_level_error = ["astral-core/release_max_level_error"]
release_max_level_warn = ["astral-core/release_max_level_warn"]
release_max_level_info = ["astral-core/release_max_level_info"]
release_max_level_debug = ["astral-core/release_max_level_debug"]
release_max_level_trace = ["astral-core/release_max_level_trace"]
