# General
edition = "2018"
version = "Two"
use_small_heuristics = "Default"
report_todo = "Unnumbered"
report_fixme = "Unnumbered"
unstable_features = true
license_template_path = ".license-apache2"

# Line breaking
newline_style = "Unix"
empty_item_single_line = true
fn_single_line = false
where_single_line = false
struct_lit_single_line = true

# Line length
max_width = 100
hard_tabs = true
tab_spaces = 4
comment_width = 100
error_on_line_overflow = false

# Identication
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
indent_style = "Block"
imports_indent = "Block"
imports_layout = "HorizontalVertical"

# Reordering
reorder_imports = true
reorder_modules = true
reorder_impl_items = true

# Modifies
force_explicit_abi = true
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
remove_nested_parens = true
condense_wildcard_suffixes = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
merge_imports = true
normalize_doc_attributes = true
trailing_comma = "Vertical"
overflow_delimited_expr = true
